### ISSUE TITLE
ServerPassword cannot be removed

### ISSUE THREAD

**Issue by twdnhfr** [chuckbutler/docker-conanexiles#1]
- "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword="
        - "CONANEXILES_Engine_OnlineSubsystemSteam_ServerPassword=''"

both settings tried but the server always starts with a the default passwort "MySecrect".

**Comment by lazypower** [comment]
Ugh thats my bad, i either cargo-culted in this hard-coded value or placed it there and forgot i had done that. the fix is to adjust:

https://github.com/lazypower/docker-conanexiles/blob/bbe9132bb411ae72cf30ccc32b42f4293cc0c397/docker-compose.yml#L10

and either pass that in as an env var and use the variable or to hard-code your no-password value there. I haven't touched this container build in quite some time, i had encountered some issues where world bosses that are LUA scripted would just remain dormant and you'll find a spew of error messaging in the container.

I suspect why after initial bootstrap you were unable to remove the password is because that gets embedded in teh server config and would need to be manually edited to remove that value. ymmv here as i'm going from memory of what the container actually does

But best of luck on your journey!

**Comment by twdnhfr** [comment]
thanks a lot!
